"""
File Storage Module
Handles saving crawled content to proper folder structure
"""

from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import git
import logging

logger = logging.getLogger(__name__)


class FileStorage:
    """Manage file storage and git operations"""

    def __init__(self, base_path: str = "."):
        self.base_path = Path(base_path)
        self.repo = self._init_git()

    def _init_git(self) -> Optional[git.Repo]:
        """Initialize or open git repository"""
        try:
            repo = git.Repo(self.base_path, search_parent_directories=True)
            logger.info(f"Using git repo: {repo.working_tree_dir}")
            return repo
        except git.InvalidGitRepositoryError:
            logger.warning("Not a git repository, git operations disabled")
            return None

    def save_content(
        self,
        content: Dict[str, str],
        folder: str,
        subfolder: Optional[str] = None,
    ) -> List[str]:
        """
        Save content to specified folder structure

        Args:
            content: Dict mapping filename to content
            folder: Main folder (e.g., 'backend/01_java-core')
            subfolder: Optional subfolder for topic (e.g., 'oop')

        Returns:
            List of saved file paths
        """
        target = self.base_path / folder
        if subfolder:
            target = target / subfolder

        target.mkdir(parents=True, exist_ok=True)

        saved = []
        for filename, text in content.items():
            if not text.strip():
                continue

            filepath = target / filename
            filepath.write_text(text, encoding="utf-8")
            saved.append(str(filepath))
            logger.info(f"Saved: {filepath}")

        return saved

    def commit_changes(self, message: str, files: Optional[List[str]] = None):
        """Commit changes to git"""
        if not self.repo:
            logger.warning("No git repo, skipping commit")
            return

        try:
            # Stage files
            if files:
                for f in files:
                    self.repo.git.add(f)
            else:
                self.repo.git.add("-A")

            # Check if there's anything to commit
            if not self.repo.is_dirty():
                logger.info("No changes to commit")
                return

            # Commit
            commit = self.repo.index.commit(
                message,
                author="FullstackLearningBot <bot@fullstack-learning.local>",
            )
            logger.info(f"Committed: {message} ({commit.hexsha[:7]})")
            return commit

        except Exception as e:
            logger.error(f"Git commit failed: {e}")
            return None

    def create_branch(self, branch_name: str, base_branch: str = "main") -> bool:
        """Create new branch for crawl work"""
        if not self.repo:
            return False

        try:
            # Handle detached HEAD state
            try:
                current = self.repo.active_branch.name
            except TypeError:
                # Detached HEAD, checkout base_branch first
                self.repo.git.checkout(base_branch)
                current = base_branch

            if current != base_branch:
                self.repo.git.checkout(base_branch)

            # Create and checkout new branch
            self.repo.git.checkout("-b", branch_name)
            logger.info(f"Created branch: {branch_name} from {base_branch}")
            return True

        except Exception as e:
            logger.error(f"Failed to create branch: {e}")
            return False

    def create_pr_description(self, source: str, files: List[str]) -> str:
        """Generate PR description for crawled content"""
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        desc = f"""# Crawl Import - {source}

## Summary
Auto-generated content from {source}
Crawled at: {date}

## Files Added/Modified ({len(files)} files)
"""

        for f in files[:20]:  # Limit list
            desc += f"\n- `{f}`"

        if len(files) > 20:
            desc += f"\n- ... and {len(files) - 20} more"

        desc += f"""

## Source
- **URL**: {source}
- **Crawler**: FullstackLearningBot

## Checklist
- [ ] Review content accuracy
- [ ] Fix formatting issues
- [ ] Add missing examples
- [ ] Verify links work
- [ ] Remove duplicates

---
*Generated by FullstackLearningBot*
"""
        return desc

    def get_existing_files(self, folder: str) -> List[str]:
        """List existing files in folder"""
        target = self.base_path / folder
        if not target.exists():
            return []

        return [str(f) for f in target.glob("**/*.md")]
